### ISSUE TITLE
No visible @interface for 'unityARCaller' declares the selector 'receivedMessageFromUnity:'

### ISSUE THREAD

**Issue by binita12345** [yasirkula/UnityIonicIntegration#10]
I have followed each and every steps of UnityIonicIntegration to complete integration of unity to ionic . 

my code in .m file 

    - (void)sendMessageToIonic:(NSString*)message
    {
    //    [self setTitleOfButtonNamed:buttonOne withTitle:btnOneTitle];
         [self.ionicComms receivedMessageFromUnity:message];
    }
I have also tried to put same parameter as a method declaration .h file 

- (void)sendMessageToIonic:(NSString*)message;

still i am getting above error. so, how could i solve this error?

**Comment by yasirkula** [comment]
Can you confirm that there exists a unityARCaller.h file at "src/ios/" of your Ionic project with the contents of this one: https://github.com/yasirkula/UnityIonicIntegration/blob/master/UnityArCallerPluginIonic/src/ios/unityARCaller.h

If not, or if unityARCaller.h is not visible in your Xcode project, then you should try readding the plugin to your project.

**Comment by binita12345** [comment]
yes, there exists a unityARCaller.h file at "src/ios/", still issue is coming.

**Comment by yasirkula** [comment]
Can you try removing the plugin and adding it again using the following command:

ionic cordova plugin add https://github.com/kevin-smets/UnityIonicIntegration.git#1.0.0

It's a fork of the plugin that can be installed through git. You can also try removing platform ios and adding it again.

If that doesn't solve the problem, then I am unfortunately out of ideas here.
