### ISSUE TITLE
Apple Mach-O Linker Error Group clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by binita12345** [yasirkula/UnityIonicIntegration#11]
I follow all steps of UnityIonicIntegration plugin, i facing above error in xCode,
how can i do to solve this error from xCode?

**Comment by yasirkula** [comment]
Have you tried the solutions posted on Google, like this one: https://stackoverflow.com/questions/12591711/mach-o-link-error-linker-command-failed-with-exit-code-1-use-v-to-see-invocat

Also, if you are building to an emulator, please try to build to an actual device.
