### ISSUE TITLE
Errors in main.mm file : Use of undeclared identifier

### ISSUE THREAD

**Issue by royken** [yasirkula/UnityIonicIntegration#12]
Hello,
thank you for this tutorial. Followed all the steps, but in the main.mm file i have the following
 errors: (screen the image bellow)
- use of undeclared identifier  'UnityParseCommandLine'
- use of undeclared identifier 'nil'
- use of undefined identifier 'NSLog' 
![20171031_183039](https://user-images.githubusercontent.com/7059358/32239084-dbe10130-be69-11e7-9b61-117e1526a2ed.jpg)
Sorry for the image quality

This is the file content:
`#include "RegisterMonoModules.h"
#include "RegisterFeatures.h"
#include <csignal>

// Hack to work around iOS SDK 4.3 linker problem
// we need at least one __TEXT, __const section entry in main application .o files
// to get this section emitted at right time and so avoid LC_ENCRYPTION_INFO size miscalculation
static const int constsection = 0;

void UnityInitTrampoline();

// WARNING: this MUST be c decl (NSString ctor will be called after +load, so we cant really change its value)
const char* AppControllerClassName = "AppDelegate";

int main(int argc, char* argv[])
{
    @autoreleasepool
    {
        UnityInitTrampoline();
        UnityParseCommandLine(argc, argv);
        
        RegisterMonoModules();
        NSLog(@"-> registered mono modules %p\n", &constsection);
        RegisterFeatures();
        
        // iOS terminates open sockets when an application enters background mode.
        // The next write to any of such socket causes SIGPIPE signal being raised,
        // even if the request has been done from scripting side. This disables the
        // signal and allows Mono to throw a proper C# exception.
        std::signal(SIGPIPE, SIG_IGN);
        
        UIApplicationMain(argc, argv, nil, [NSString stringWithUTF8String:AppControllerClassName]);
    }
    
    return 0;
}

#if TARGET_IPHONE_SIMULATOR && TARGET_TVOS_SIMULATOR

#include <pthread.h>

extern "C" int pthread_cond_init$UNIX2003(pthread_cond_t *cond, const pthread_condattr_t *attr)
{ return pthread_cond_init(cond, attr); }
extern "C" int pthread_cond_destroy$UNIX2003(pthread_cond_t *cond)
{ return pthread_cond_destroy(cond); }
extern "C" int pthread_cond_wait$UNIX2003(pthread_cond_t *cond, pthread_mutex_t *mutex)
{ return pthread_cond_wait(cond, mutex); }
extern "C" int pthread_cond_timedwait$UNIX2003(pthread_cond_t *cond, pthread_mutex_t *mutex,
                                               const struct timespec *abstime)
{ return pthread_cond_timedwait(cond, mutex, abstime); }

#endif // TARGET_IPHONE_SIMULATOR && TARGET_TVOS_SIMULATOR
`

**Comment by yasirkula** [comment]
In your screenshot, there are two Data directories listed under Unity group. There should only be one Data directory there. Guess you dragged Data instead of Classes by mistake.

**Comment by royken** [comment]
Thank you @yasirkula !!!

**Comment by scarffy** [comment]
Hi guys,

I have kind of similar problem.

I followed the tutorial but I this error 'use of undeclared identifier' on UnityInitStartupTime(); and UnityInitRuntime(argc, argv);

<img width="1324" alt="screen shot 2018-05-08 at 11 02 36 am" src="https://user-images.githubusercontent.com/34879344/39735728-7a29147a-52af-11e8-870f-d454eb922dd2.png">

**Comment by yasirkula** [comment]
Can you show the contents of the Unity group in Xcode?

**Comment by scarffy** [comment]
Here it is. 

<img width="373" alt="screen shot 2018-05-08 at 2 51 24 pm" src="https://user-images.githubusercontent.com/34879344/39742236-58f32a6e-52cf-11e8-9d79-34e95fbcb65a.png">

**Comment by yasirkula** [comment]
If you are trying to test the app on a simulator, can you also try to test it on a real device and see if it changes anything? Unity produces slightly different output for simulators (see [Target SDK/SDK Version](https://docs.unity3d.com/Manual/class-PlayerSettingsiOS.html)), so it might be the issue here. Otherwise, if you have made all the adjustments to both _PROJECT_ and _TARGETS_ in Build Settings correctly, I couldn't spot the issue at first glance.

**Comment by scarffy** [comment]
Unfortunately, the error doesn't go away when I try to test it on a real device. :(

**Comment by yasirkula** [comment]
If you are sure that you have set all the configurations to _unityconfig_ and that you have set the value of _UNITY_IOS_EXPORTED_PATH_ to the path of **your** Unity build directory (not the one in the screenshot) for both _PROJECT_ and _TARGETS_, then I guess any help is welcome at this point.

**Comment by scarffy** [comment]
I am quite sure I set up this properly. Here's my screenshot of UNITY_IOS_EXPORTED_PATH and also in config

<img width="859" alt="screen shot 2018-05-08 at 4 39 26 pm" src="https://user-images.githubusercontent.com/34879344/39746951-7d45633c-52de-11e8-9813-41f08071ba13.png">

<img width="1132" alt="screen shot 2018-05-08 at 4 42 02 pm" src="https://user-images.githubusercontent.com/34879344/39747067-d00c41d0-52de-11e8-8012-e2c52bcbc88f.png">

<img width="863" alt="screen shot 2018-05-08 at 4 44 33 pm" src="https://user-images.githubusercontent.com/34879344/39747194-25a078dc-52df-11e8-8862-d79964a99d21.png">

**Comment by yasirkula** [comment]
Can you show the contents of /Users/Scarffy/Desktop/iOSNativeApp, as well? Just to be sure, if it is OK.

**Comment by scarffy** [comment]
Here you go.

<img width="315" alt="screen shot 2018-05-08 at 5 08 55 pm" src="https://user-images.githubusercontent.com/34879344/39748377-824b90aa-52e2-11e8-864c-14dd30ad82e2.png">

**Comment by yasirkula** [comment]
Thank you for providing all the info. Looking at the screenshots, everything does seem to be in order; and I currently have no clues to fix this error.

**Comment by scarffy** [comment]
That's a bummer. Thanks for trying to solve this issue.

**Comment by mateenagy** [comment]
At first I also get this kind of error and I am not sure how I solved this but try again the whole thing again.  I also change the unityconfig.xconfig _UNITY_RUNTIME_VERSION_ to the version I used but I don't think this is the problem. Maybe you missed something somewhere. When I tried to make it work it took me around 4 day to figure everything out. :D I also wrote a php script for changing the files after export which makes these steps a little bit faster. I will post this script today and you can try with that if you want.

**Comment by yasirkula** [comment]
A video tutorial sounds nice but neither my current setup nor my motivation is ready for it :/ Sorry.

**Comment by mateenagy** [comment]
@scarffy Yes it can cause the problem. When you click on the prefix header and press **DELETE** it changes the path to the unity folder. And you need to do this in the _TARGET_ and in the _PROJECT_

**Comment by scarffy** [comment]
@yasirkula No problem :)
@mateenagy From my screenshot, it should be correct. I tried with unity 2017.1 but it's the same thing. Maybe different xcode version that cause it? 

Yasir using xcode 8.3.3 while I'm using xcode 9.3.1

**Comment by yasirkula** [comment]
If your Unity build path is /Users/Scarffy/Desktop/iOSNativeApp, then both of them should point to /Users/Scarffy/Desktop/iOSNativeApp/Classes/Prefix.pch. When you select them and press Delete, the value should automatically revert to it.

**Comment by mateenagy** [comment]
No I also use Xcode 9.3.1 with Unity 2017.1 and 2018 and everything works well. I also use with the newest Vuforia(only Vuforia or camera usage can be cause problem in Xcode 9.3, but not like this). But yasirkula is right, both of the Prefix Header path should be the same if you delete them.

**Comment by scarffy** [comment]
It shouldn't make any different if I don't use vuforia right?
I can also confirm my Prefix Header path is correct. It point to /Users/Scarffy/Desktop/iOSNativeApp/Classes/Prefix.pch.

**Comment by mateenagy** [comment]
@scarffy There is no difference. Did you set the prefix header for both _TARGET_ and _PROJECT_?

**Comment by scarffy** [comment]
Hi Guys, I think I run out of luck with this plugin. I'm not sure where I went wrong, I just can't make it work.

**Comment by yasirkula** [comment]
Did it work on a blank project, though?

**Comment by mateenagy** [comment]
@scarffy Can you upload the blank project you made to github so I or we can check your code?

**Comment by scarffy** [comment]
@yasirkula @mateenagy @jbgtmartin Happy news guys! I managed to make it work. From the bottom of my heart, I truly thank you for the help you guys give me.

I missed out @jbgtmartin comment. My prefix header for TARGET is already right but not for PROJECT. After I build, I ran to this error #15 which is easily solved.

**Comment by yasirkula** [comment]
Glad to hear it!
