### ISSUE TITLE
Intergrate with Ionic V1 project

### ISSUE THREAD

**Issue by royken** [yasirkula/UnityIonicIntegration#13]
Please how to use it with Ionic V1 project ? Thank you

**Comment by yasirkula** [comment]
What happens when you follow the steps in the documentation?

**Comment by royken** [comment]
@yasirkula in Ionic V1 for example we do not have variables declaration like 
`declare let unityARCaller: any;`
Everuthing is ok for the plugin intergration, but how to call functions ?

**Comment by binita12345** [comment]
yes, @yasirkula I have same question in this plugin.
how to call functions from ionic1 project, which functions used in unity javascript?

**Comment by yasirkula** [comment]
@royken can you try changing that line to this:

`var unityARCaller: any;`

Source: https://stackoverflow.com/a/40700848/2373034

**Comment by yasirkula** [comment]
@binita12345 if your script is named AnimationPlayer.js and it is attached to a gameobject with name "MyObject", you have two options:

- In OnMessageReceivedFromIonic function of IonicComms.cs, insert the following code:

`GameObject.Find( "MyObject" ).GetComponent<AnimationPlayer>().Start();`

This code will be executed as soon as Unity content has launched. If this function gives an error, try moving AnimationPlayer.js to Plugins folder of your project (create one, if it doesn't exist).

- In IonicComms.cs, add the following function:

```
public void PlayAnimation( string message )
{
	GameObject.Find( "MyObject" ).GetComponent<AnimationPlayer>().Start();
}
```

This function will be executed whenever you call the following function in your Ionic code:

`unityARCaller.sendMessage( "PlayAnimation", "" );`
