### ISSUE TITLE
 Error:Failed to resolve: :VuforiaWrapper:

### ISSUE THREAD

**Issue by ianrothmann** [yasirkula/UnityIonicIntegration#14]
Hi there,

I am using Unity 2017.3.0f3 with Vuforia 7.0.36. I now get this error 
`Error:Failed to resolve: :VuforiaWrapper: when syncing.`

I suspect it has to do with this in build.gradle for the UnityProject

```
dependencies {
	compile fileTree(dir: 'libs', include: ['*.jar'])
	compile(name: 'VuforiaWrapper', ext:'aar')
}
```
I used to build with Unity 2017.2.0b10, and the VuforiaWrapper dependency was not there. When I remove that dependency the project builds, but of course Vuforia does not work.

Any ideas? The error only occurs when integrating, meaning that I can build the Unity Grade project on its own without problems.

Much appreciated!

Ian

Ps. Seems like this individual has a similar problem: https://developer.vuforia.com/forum/unity/error-import-unity-project-android-studio

**Comment by yasirkula** [comment]
I found a solution to this problem but I couldn't test it with an Ionic project but rather with an empty Android project; so, you may need to adjust the solution a little in your case.

What I did was simply pasting the following code to the top of **build.gradle** of the **android** module:

```
allprojects {
    repositories {
        flatDir {
            dirs 'C:\\absolute path\\to your\\unity export folder\\libs'
        }
    }
}
```

**Comment by ianrothmann** [comment]
Thank you very much! This works perfectly.
