### ISSUE TITLE
iOS - Thread 1: EXC_BAD_ACCESS (code=1, address=0x30)

### ISSUE THREAD

**Issue by ianrothmann** [yasirkula/UnityIonicIntegration#15]
After integration, when running on iOS, the app opens and the Ionic side is working. When I tap on the button that starts Unity (using the openUnity() method) I'm getting the following error: 
`Thread 1: EXC_BAD_ACCESS (code=1, address=0x30)`

Here are screenshots of exactly what's happening:

[https://pasteboard.co/H39PlhX.png](https://pasteboard.co/H39PlhX.png)
[https://pasteboard.co/H39YwmR.png](https://pasteboard.co/H39YwmR.png)

Using Unity 2017.3.0f3, Ionic 3.19.0, Cordova 7.1.0. In the current scenario, the Unity project only contains a blank scene (with the integration scripts and files). We're also not using Vuforia for now. The Ionic project is a bare minimum too (only one button calling openUnity(), and the plugin). 

We have tried building several times on different Macs and different devices. I'm pretty sure we're not missing any steps.

Any ideas?

Appreciate the help!

Ian

Ps. Just to be thorough, here is an ionic info dump:

cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:
    cordova (Cordova CLI) : 7.1.0 

local packages:
    @ionic/app-scripts : 3.1.6
    Cordova Platforms  : ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:
    ios-deploy : 1.9.2 
    Node       : v8.9.1
    npm        : 5.5.1 
    OS         : macOS Sierra
    Xcode      : Xcode 9.2 Build version 9C40b

**Comment by ianrothmann** [comment]
So I managed to fix the issue based on [this thread](https://forum.unity.com/threads/il2cpp-anyone-else-seeing-metadatacache-initialize-crashes-sometimes-when-the-game-starts.383145/).

It seems that you need to add -DRUNTIME_IL2CPP=1 in Other C flags and Other C++ Flags (for both project and target) under Apple LLVM custom compiler flags in build settings. Make sure that you delete the app completely from your phone and run it again. It should work.

**Comment by yasirkula** [comment]
Is it also an `EXC_BAD_ACCESS (code=1, address=0x30)` error?

**Comment by ataylor09** [comment]
Hi @yasirkula, @ianrothmann .... I'm still getting an error even after applying the fix described above.
`EXC_BAD_ACCESS (code=1, address=0x30)`
Here is a screenshot, have I applied the flags correctly?

<img width="819" alt="screen shot 2019-02-27 at 5 34 18 pm" src="https://user-images.githubusercontent.com/5655773/53466291-3fc75e00-3ab6-11e9-8227-3a391b2b8fa2.png">

**Comment by yasirkula** [comment]
Did you add these flags to both _PROJECT_ and the _TARGETS_? And did you delete the app from your phone before running the project again?

Does this issue also occur on a fresh new Unity project? Are you testing on a simulator or on an actual device? Is the issue persistent across different Unity versions?
