### ISSUE TITLE
Lessons learnt with Vuforia 7 and Unity 2017.3.0f3 

### ISSUE THREAD

**Issue by ianrothmann** [yasirkula/UnityIonicIntegration#16]
Hi everyone,

I'm posting this here just to let other users know of some lessons learnt / changes we've experienced using Vuforia 7 and the new Unity.

Unity Side Setup
- In Player settings->Other Settings: Camera Usage Description must be specified and Target minimum iOS version must be >= 9.0
- In Player settings->XR Settings: Vuforia Augmented Reality must be enabled

iOS Side Setup
- For Vuforia users: Drag & drop Data/Raw/Vuforia instead of Data/Raw/QCAR(which does not exist) from the Unity build directory to the Unity group in Xcode
- For Vuforia users: Move VuforiaNativeRendererController.mm from Libraries(in Unity group in Xcode) to Libraries/Plugins/iOS(in Unity group in Xcode)
- Have a look at #15 
- You might need to specify the Camera Usage Description in Xcode.

Android setup
- Have a look at issue #14 

Kind regards,

Ian

**Comment by yasirkula** [comment]
Added a link to this on README.

**Comment by ppkantorski** [comment]
For some reason I cant find  Data/Raw/Vuforia nor Data/Raw/QCAR.  There is a QCAR folder in my Unity build folder with a file called "somedata16".  Is that the folder that we need to copy over?
