### ISSUE TITLE
UnitySetGraphicsDevice and UnityRenderEvent cause link errors

### ISSUE THREAD

**Issue by Frobei** [yasirkula/UnityIonicIntegration#2]
Hi,

I'm trying to follow your tutorial to see how to link a Cordova project with Unity on iOS (without Vuforia for now) and I got linking errors that prevent me to compile:
Undefined symbols for architecture armv7:
  "_UnitySetGraphicsDevice", referenced from:
      -[AppDelegate shouldAttachRenderDelegate] in AppDelegate.o
  "_UnityRenderEvent", referenced from:
      -[AppDelegate shouldAttachRenderDelegate] in AppDelegate.o

Do I need to add a framework ? Because I couldn't find their definition anywhere.

**Comment by yasirkula** [comment]
- Make sure that the path of your Xcode project and/or Unity project do not contain any space character(s)

- Try adding `#import "UnityAppController.h"` to AppDelegate.mm

- Also make sure that you have completed these steps:

> In Configurations of your project, set all the configurations as unityconfig

> In Build Settings, set the value of UNITY_IOS_EXPORTED_PATH to the path of your Unity iOS build folder (do this for PROJECT and the TARGETS)

> In Build Settings, select Prefix Header and press Delete to revert its value back to the default value (in case it is overridden)(do this for PROJECT and the TARGETS)

- Do the Delete thing to "Header Search Paths" and "Library Search Paths" in Build Settings, as well (do this for PROJECT and the TARGETS)

Please let me know if any of these steps work for you.

**Comment by Frobei** [comment]
I made sure to thoroughly follow the steps, and I just did it one more time but I still have the same linking problem. 
Can you explain me the role of the methods UnitySetGraphicsDevice, unityRenderEvent, UnityRegisterRenderingPlugin please ? Or maybe if you can upload a small project which works with you I can try to figure it out.
Thanks a lot !

**Comment by yasirkula** [comment]
I copied parts of that code (including the part with UnitySetGraphicsDevice and UnityRegisterRenderingPlugin) from other sources (most probably from one of the 4 sources mentioned in README), and neither do I really know the role of these methods.

I have tested this method with Vuforia but I will try to create a sample project without Vuforia and test it on it, as well. Though, I may not be able to do so this week because I need to use my workstation at work and there are plenty of tasks to complete before I can use it for my own purposes.

In the meantime, I hope you can resolve this issue and share your results with us.

**Comment by Frobei** [comment]
So I decided to try your integration with a scene using Vuforia. I had some issue with Cordova but that's only because I'm not used to this environment, hopefully I made it work eventually.

Then I came back to my first attempt with the scene which doesn't use Vuforia. I still got those linking errors and I tried to comment all the lines containing the methods mentioned above and... That's it, I was able to launch my scene through a HTML !

Thanks for giving me some of your time !

**Comment by yasirkula** [comment]
I'm glad you managed to resolve this issue. I am now even more eager to test it myself. Thanks for sharing your solution (:

**Comment by yasirkula** [comment]
I was finally able to test it on a clean project. As you said, these errors can not be solved without importing some 3rd party native rendering plugin (maybe this: https://github.com/hacksalot/unity-render-native/blob/master/src/RenderingPlugin/RenderingPlugin.cpp). 

Deleting those lines from AppDelegate does solve the linker errors. I'll be updating the repo soon.
