### ISSUE TITLE
Problem with gvr and unitygvr files

### ISSUE THREAD

**Issue by adri21112** [yasirkula/UnityIonicIntegration#21]
Hi.
I am working with a Unity 2017.3 project and I have problems to solve dependences on the Unity's build.gradle because I must to compile a gvr.aar file and unitygvr.aar file on the libs folder, this files are created with my Unity project.
The Android Studio throws "Failed to resolve: gvr" and "Failed to resolve: unitygvr"

This is my Unity build.gradle fragment:
```
allprojects {
   repositories {
      flatDir {
        dirs 'libs'
      }
   }
}

apply plugin: 'com.android.library'

dependencies {
	compile fileTree(dir: 'libs', include: ['*.jar'])
	compile(name: 'gvr', ext:'aar')
	compile(name: 'unitygvr', ext:'aar')
}
```

How can I fix that?
Thanks

**Comment by yasirkula** [comment]
These might help:

https://stackoverflow.com/a/31558348/2373034
https://stackoverflow.com/a/32546892/2373034

**Comment by adri21112** [comment]
Thanks for your tips. I resolved it with the first link. Maybe this is interesting to complete on your readme.

But now my Android Studio throw other error: 
![image](https://user-images.githubusercontent.com/8613412/37950766-1c5ad94a-319a-11e8-8aca-3659e60915c1.png)

Do you know something about this?

Sorry, I don't have experince with Android.

Thanks!!

**Comment by adri21112** [comment]
I solved it with the first link. I think this is interesting to add to your readme.
Thanks for your tip!

**Comment by yasirkula** [comment]
Will do!
