### ISSUE TITLE
'UnityAppController.h' file not found

### ISSUE THREAD

**Issue by teatherconsulting** [yasirkula/UnityIonicIntegration#22]
After following the steps I am getting the following error from Classes\AppDelegate.h:

'UnityAppController.h' file not found

I have completed and re-verified the following steps:

--In Configurations of your project, set all the configurations as unityconfig

--In Build Settings, set the value of UNITY_IOS_EXPORTED_PATH to the path of your Unity iOS build folder (do this for PROJECT and the TARGETS)

--In Build Settings, select Prefix Header and press Delete to revert its value back to the default value (in case it is overridden)(do this for PROJECT and the TARGETS)

Any ideas if there is something else that could be missing?

**Comment by yasirkula** [comment]
Hmm, that's hard to say; I am not really good at debugging Xcode errors. But for starters, where is UnityAppController.h located in your Xcode project? And what is your Unity version?

You may also want to try integrating Unity with a blank Ionic project just to see if the error will be gone.

**Comment by teatherconsulting** [comment]
For anyone else that might run into this, the issue was solved by opening the wcworkspace instead of the xcodeproj file.

**Comment by yasirkula** [comment]
Thanks, I've updated the README.
