### ISSUE TITLE
About 64-bit ARM, x86 and x64 Android Devices

### ISSUE THREAD

**Issue by adri21112** [yasirkula/UnityIonicIntegration#23]
Hi.
I want to comment something about "About 64-bit ARM, x86 and x64 Android Devices" section.
I had the same problem you coment in this section but I found the folders arm64-v8a, armeabi or x86_64 in the libs folder and not on the jniLibs.

Thank you for your fantastic plugin!!

**Comment by yasirkula** [comment]
Thank you for the comment. Are you sure that the Project view was in "Android" mode, rather than "Project" mode? By modes, I mean these:

![choose-project-view](http://tools.android.com/_/rsrc/1472841731680/recent/androidstudio084released/choose-project-view.png)

**Comment by adri21112** [comment]
Uoo!! I was working with my ionic environment and I saw libs folder. With my Android view I can see the jniLibs folder.
Sorry.

**Comment by yasirkula** [comment]
It's OK 😄 Thanks for reporting this.
