### ISSUE TITLE
'il2cpp-config.h' file not found

### ISSUE THREAD

**Issue by mateenagy** [yasirkula/UnityIonicIntegration#24]
Hi!

I am currently try to make unity vuforia and ionic work and I follow every single step, but I always get `'il2cpp-config.h'` file not found error and I cant figure out the problem.

I go through the folders and this file is in the libil2cpp folder but I deleted this folder as the tutorial said.

**Comment by mateenagy** [comment]
I found the problem i just give a wrong path, but I ran into an another issue.

The build is working and i can start the application but when the openUnity method called I getting the following error:

`EXC_BAD_ACCESS (code=1, address=0xb8)`

**Comment by yasirkula** [comment]
Can this be of any help? #15

**Comment by yasirkula** [comment]
It seems correct, if you applied the same thing to the *Apple LLVM Custom Compiler Flags* of *ar-app* under the *TARGETS*.

EXC_BAD_ACCESS errors are very annoying for me as I find them very hard to debug; maybe because I'm not good at Xcode, not sure. Currently, I don't have any clues about why that EXC_BAD_ACCESS might be happening. Please let me know if you find something new. Will do the same.

**Comment by mateenagy** [comment]
Okey I figured out what I did wrong and if anybody read the manual more carefully than me will never run into this problem. The problem was I include Data with Create groups and not with Create folder references. But I also run into issues with iOS 11.3 and xcode 9.3 so I made a new closed comment where I wrote these down and how to fix.

**Comment by LasLamos** [comment]
Im currently having the same issue.
I deleted the il2cpp folder but get the missing il2cpp-config.h error.
I'm not quite sure how to fix this.

mateenagy said he solved it by giving a different path but i'm not sure where I should set the path.

Any tips on how to solve this?

**Comment by yasirkula** [comment]
Probably he entered a wrong path here:

![image](https://raw.githubusercontent.com/yasirkula/UnityIonicIntegration/master/images/ios4.png)

Also, as a reminder:

> **IMPORTANT NOTICE:** make sure that the paths to your Ionic project and Unity build directory do not contain any space characters.

**Comment by LasLamos** [comment]
That was the problem, thanks.
Im having a different issue now but maybe I can figure it out on my own.

Thanks for the quick help
