### ISSUE TITLE
ARKit

### ISSUE THREAD

**Issue by scarffy** [yasirkula/UnityIonicIntegration#26]
Have anyone tried with ARKit?

When I try to build using this plugin I got this error, I'm not sure how to fix it.

<img width="278" alt="screen shot 2018-05-24 at 9 19 54 am" src="https://user-images.githubusercontent.com/34879344/40459412-c6d01dec-5f33-11e8-9c1e-b88d6a179a30.png">

**Comment by scarffy** [comment]
For those who want to encounter similar error, you can go to `TARGET > General`. Find `Linked Frameworks and Libraries` and add `ARKit.framework`

**Comment by yasirkula** [comment]
That was quick! Thanks for the info!

**Comment by scarffy** [comment]
You're welcome. Just want to contribute back to people.
