### ISSUE TITLE
error: cannot find symbol class UnityPlayer

### ISSUE THREAD

**Issue by bbiaudet** [yasirkula/UnityIonicIntegration#28]
Hello, I encounter a compilation problem under android studio 3.1.2, when I delete the unity-classes.jar file in the libs folder of the android project, I have 7 compilation errors:

```
error: can not find UnityPlayer class symbol
error: can not find symbol class UnityPlayerActivity
error or method not applicable or a method from a supertype
error: registerReceiver (IonicToUnityBroadcastReceiver, IntentFilter)
error or method not applicable or a method from a supertype
error: can not find symbol variable super
error: can not find symbol method setResult (Int, Intent)
```

**Comment by bbiaudet** [comment]
Yes I changed the way and the project unity is well linked in the project android studio.

![capture d ecran 2018-05-30 a 11 33 05](https://user-images.githubusercontent.com/16972115/40712168-51f15364-63fd-11e8-88c3-1fa67d5370cb.png)

**Comment by yasirkula** [comment]
Is there a unity-classes.jar located at UnityProject/libs? If so, can you verify that you've put `compile project(':UnityProject')` to the correct location?

**Comment by bbiaudet** [comment]
Yes is located at UnutyProject/libs.

![capture d ecran 2018-05-30 a 12 44 00](https://user-images.githubusercontent.com/16972115/40715880-5cce1448-6407-11e8-879c-2deed2811d47.png)

If I leave the .jar in the android project I have a double class loading error

**Comment by yasirkula** [comment]
Does changing `implementation project(':UnityProject')` to `compile project(':UnityProject')` or `api project(':UnityProject')` solve the issue?

**Comment by bbiaudet** [comment]
no for api some error, for compile error is obsolete

**Comment by bbiaudet** [comment]
![capture d ecran 2018-05-30 a 13 26 57](https://user-images.githubusercontent.com/16972115/40717603-3e5dd376-640d-11e8-938e-cbdd7e7492c2.png)

**Comment by yasirkula** [comment]
At this point, any help is appreciated.

**Comment by bbiaudet** [comment]
I managed the compilation, I just downgrade Gradle 4.4. at 3.5.

thanks again for help

**Comment by yasirkula** [comment]
That's great news! I may update the README if someone else encounters the same issue, as well.

**Comment by bbiaudet** [comment]
Yep!
