### ISSUE TITLE
ngFactory issue with Android project

### ISSUE THREAD

**Issue by syc-pad** [yasirkula/UnityIonicIntegration#3]
Hello,
First of all, thanks for your ressources and your explanations. I followed it for an Android project, and everything related to Android part works well (I'm an Android native dev, it may helps... :) but I'm Ionic and Unity newbie).

My sample app is pretty simple : I put a button on the home page, and when I click on it, it calls openUnity().

But when I click the button, I see in the Android Logcat : 
```
D/SystemWebChromeClient: ng:///AppModule/HomePage.ngfactory.js: Line 115 : ERROR
06-01 01:23:13.830 17298-17298/io.ionic.starter I/chromium: [INFO:CONSOLE(115)] "ERROR", source: ng:///AppModule/HomePage.ngfactory.js (115)
06-01 01:23:13.833 17298-17298/io.ionic.starter D/SystemWebChromeClient: ng:///AppModule/HomePage.ngfactory.js: Line 115 : ERROR CONTEXT
06-01 01:23:13.833 17298-17298/io.ionic.starter I/chromium: [INFO:CONSOLE(115)] "ERROR CONTEXT", source: ng:///AppModule/HomePage.ngfactory.js (115)
06-01 01:23:13.843 17298-17298/io.ionic.starter W/cr_Ime: updateState: type [0->0], flags [0], show [false],
```

...and nothing happens. The app doesn't crash, but nothing happens. However, the Unity project alone works well : I already built it and deployed as a standalone app, and it works fine.

As I'm a newbie in Ionic, I may be missing something, but I don't understand clearly what. Your sample code makes me think I wouldn't have to call the Unity activity with the Ionic NavController navCtrl.push() method like we should do in a normal "launch new Activity" context.

However, if a change my Ionic button behaviour, and make it call a dummy function (displaying a simple alert dialog with a dummy message), it works. (hopefully !! ^^ if not I'd better worry)

Could you please give more info/context/details about calling this.unityARCaller.launchAR(...) ?
Thanks.

Here is my very simple **home.ts** file : 
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  unityARCaller: any;

  constructor(public navCtrl: NavController) {

  }

  openUnity() {
  	// it is possible to send a string message to Unity-side (optional)
  	this.unityARCaller.launchAR("my message for Unity-side", this.uSuccessCallback, this.uFailedCallback );
  }

  uSuccessCallback = (param) => {
	   // param:String is the (optional) message received from Unity-side
	//  alert( param );
  };

  uFailedCallback = (error) => {
  	// should ignore this callback
  };

  openAR(){
    // alert("Launch AR")
    this.openUnity();
  }
}
```

And my (as simple as previous one) **home.html** file : 
```
<ion-header>
  <ion-navbar>
    <ion-title>
      Ionic Blank
    </ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
  <button ion-button (click)="openAR()">Start AR</button>
</ion-content>
```

I'm running Ionic 3.0.0, Cordova 7.0.1

**Comment by syc-pad** [comment]
I noticed something strange : in the UnityProject Manifest.xml, I've got an activity whose name is com.unity3d.player.VideoPlayer. (I removed the launching activity that had the intent filters Launcher + Default)
It seems Android can't resolve the VideoPlayer, but it doesn't prevent me to build and run the app...

**Comment by syc-pad** [comment]
After some further research, I read about past AOT problems some months ago with ngFactory and typescript 2.1, but their problems occurred during build, apparently, whereas I can build and run successfully. Besides, I'm using typescript 2.3.3, and I'm guessing this issue has been solved for a long time.

**Comment by yasirkula** [comment]
Hi there!

`com.unity3D.player.UnityPlayer` is, as you said, an internal class of Unity that shouldn't be changed. It is located inside src/android/unity-classes.jar of my plugin, which is copied to libs folder of your project upon building your Ionic project to Android. As Ionic is able to find the UnityPlayer class inside the jar archive, it doesn't give any errors while building. But we delete this unity-classes.jar from project in Android Studio because Android builds of Unity projects already contain an up-to-date version of unity-classes.jar (namely, classes.jar) and we wouldn't want any duplicates in our Android Studio project (one coming from Ionic plugin and one coming from Unity).

I also have the `com.unity3d.player.VideoPlayer` activity in my manifest, it shouldn't cause any issues in this case. UnityPlayerNativeActivity and UnityPlayerProxyActivity are deprecated classes which are now replaced with com.unity3d.player.UnityPlayerActivity. Their existence (or non-existence) in AndroidManifest should not cause any issues as my plugin launchs com.unitycaller.ionic.UnityPlayerExtendedActivity which extends UnityPlayerActivity.

Coming back to your question; can you try this TypeScript code and let me know the result:

```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})

declare let unityARCaller: any;

export class HomePage {

  constructor(public navCtrl: NavController) {

  }

  uSuccessCallback = (param) => {
	// param:String is the (optional) message received from Unity-side
	//  alert( param );
  };

  uFailedCallback = (error) => {
  	// should ignore this callback
  };

  openAR(){
	// alert("Launch AR")
	// it is possible to send a string message to Unity-side (optional)
	unityARCaller.launchAR("my message for Unity-side", this.uSuccessCallback, this.uFailedCallback );
  }
}
```

**Comment by syc-pad** [comment]
OMG !!! THANK YOU VERY MUCH !!
Merci beaucoup !! 👍 
Honestly, as I'm a newbie with Ionic3, as I did't manage to write the declaration of unityARCaller at a place in the code where no lint error was fired... I made it like you saw. Didn't know we could write like this... and how much this detail changes everything !

Little precision : I had to write the declaration before the @Component, if not I had an error.

Just one question : my Unity view is very dark, and my phone isn't able to adapt light sensibility (like it would do normally when I take photo/video). Is it normal ? I already made some similar AR experimentations with Vuforia alone (without Unity), and the behaviour then was normal. Is it a Unity side effect ?

**Comment by yasirkula** [comment]
Glad it worked!

If your camera image is too dark, then all I can suggest is that you try to change the camera focus mode to FOCUS_MODE_CONTINUOUSAUTO (https://library.vuforia.com/articles/Solution/Camera-Focus-Modes). If not, maybe someone on Vuforia forums may have a solution for this problem already.

If your Unity scene is too dark, then you can make sure that there is a directional light in the scene and if so, you can tweak its Intensity or open Window-Lighting-Settings and tweak the Ambient light parameters.
