### ISSUE TITLE
iOS - Error opening the Unity Activity - NSInvalidArgumentException: [NSNull UTF8String]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by bdomingues** [yasirkula/UnityIonicIntegration#32]
Hello,

I'm building a cross platform app using Ionic + Unity with Vuforia, and its currently working smoothly with Android.
I've been struggling with making it work properly in iOS. As soon as I launch unity, the splash screen shows up and the app crashes with the following error:

`Uncaught exception: NSInvalidArgumentException: -[NSNull UTF8String]: unrecognized selector sent to instance 0x1b2da0650'`

It also points to the following line on Other sources/main.mm
![captura de ecra 2018-07-09 as 03 49 55](https://user-images.githubusercontent.com/15131832/42428349-2cc6ca18-832b-11e8-8443-f6dd579cb1ab.png)

Full log:
https://pastebin.com/raw/jHfSXZ2s

I've searched around and no one seems to be having this issue.
Any clue? my main.mm seems fine.

Thanks.

**Comment by yasirkula** [comment]
This should fix the issue: https://github.com/yasirkula/UnityIonicIntegration/commit/672026213463920fbdcf49ec2bac6e56fb19b1c0

**Comment by bdomingues** [comment]
Seems like it is working ! Thanks
