### ISSUE TITLE
Semantic issues (UnityAppController.h) with latest version 

### ISSUE THREAD

**Issue by ShaliniShanmugam7** [yasirkula/UnityIonicIntegration#35]
I am trying to integrate mapbox unity project with ionic ios project.I followed all the iOS steps and ended up with this lexical or preprocessor issue.

Unity version 2018.2.3f1
mapbox https://www.mapbox.com

**Comment by yasirkula** [comment]
First, try integrating an empty Unity project with Ionic. If it works, then try applying this solution: https://github.com/yasirkula/UnityIonicIntegration/issues/27

**Comment by ShaliniShanmugam7** [comment]
#import <UIKit/UIKit.h>


Added the above import line at the top. Issues cleared. But still facing **many semantic issues** under "Classes/Unity"  - objective C files

**Comment by ShaliniShanmugam7** [comment]
Under the Build Settings in xCode. But still the issues are there. only once it cleared. I downgraded the unity 2018 to unity 2017. Still am getting plenty of semantic issues. Please help.

**Comment by yasirkula** [comment]
If **Prefix.pch** inside the Unity group doesn't have `#import <UIKit/UIKit.h>` and/or `#import <Foundation/Foundation.h>` in-between `#ifdef __OBJC__` and `#endif` lines, try adding them.

**Comment by ShaliniShanmugam7** [comment]
Its already present in Prefix.pch. still not able to clear the issues

**Comment by yasirkula** [comment]
Try adding `#import <UIKit/UIKit.h>` to UnityAppController.h manually.

**Comment by ShaliniShanmugam7** [comment]
Thanks @yasirkula . After fixing this i am getting similar semantic issues in "UnityAppController" is fixed. I still have semantic errors in **UnityAppController+UnityInterface** file
<img width="672" alt="error" src="https://user-images.githubusercontent.com/42229279/45729557-80fe3c80-bbff-11e8-88b5-9c2b43f4397e.png">

**Comment by ShaliniShanmugam7** [comment]
I fixed it by setting prefix header path in build settings. 

Referred - https://github.com/yasirkula/UnityIonicIntegration/issues/12

**Comment by yasirkula** [comment]
This is the correct fix. I will add instructions for when the prefix header path is blank to the README: https://github.com/yasirkula/UnityIonicIntegration/issues/12#issuecomment-389437474

**Comment by ShaliniShanmugam7** [comment]
All looks same. but not able to clear this clang error

**Comment by yasirkula** [comment]
How about Header Search Paths and/or Library Search Paths? Are there any additional paths in Unity Xcode project?

**Comment by ShaliniShanmugam7** [comment]
checked and added the additional paths like mapbox. now got this below error. somewhere its missing the linking. 
<img width="444" alt="apple error" src="https://user-images.githubusercontent.com/42229279/45752025-c2660a80-bc46-11e8-99f9-ca1acad407a5.png">

**Comment by ShaliniShanmugam7** [comment]
I fixed this apple mach o linker error by adding "Storekit Framework".

Reference : https://forum.unity.com/threads/solved-tvos-undefined-symbols-for-architecture-arm64.504684/

finally app is crashing 

[6576:3057309] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UnityAppController 0x1c0109ea0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key unityController.'
*** First throw call stack:
(0x182197164 0x1813e0528 0x182196e2c 0x182b4a434 0x182a90e20 0x102d53a8c 0x1037a9ab4 0x103669c88 0x103030b60 0x18b7c02c4 0x18b9b1bc4 0x18b9b6a14 0x18bc522a8 0x18bf2a100 0x18bc51f0c 0x18bc5276c 0x18c3d77c0 0x18c3d7664 0x18c1452cc 0x18c2de3cc 0x18c14517c 0x18bf29760 0x18b9b5158 0x18bdcadbc 0x18485a1f0 0x184862af8 0x10747d28c 0x1074899e4 0x18488e7f8 0x18488e49c 0x18488ea38 0x18213f77c 0x18213f6fc 0x18213ef84 0x18213cb5c 0x18205cc58 0x183f08f84 0x18b7b55c4 0x10235d1a4 0x181b7c56c)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by ShaliniShanmugam7** [comment]
After clearing all the compilation errors. I am able to get successful build. but  the app is crashing with below error in Other sources "main.mm" file.

here is the screenshot. any suggestions would be helpful.

<img width="833" alt="app crash" src="https://user-images.githubusercontent.com/42229279/45795378-0c460380-bcce-11e8-9c18-49f88bed1f0a.png">

**Comment by ShaliniShanmugam7** [comment]
Solution to clear all the semantic issues - Add all required frameworks (i compared with unity ios project) under General - linked frameworks and libraries. Redo the integration ios steps.


add the key and value in Info.plist

Key    :  Privacy - Camera Usage Description   
Value  :  $(PRODUCT_NAME) camera use
