### ISSUE TITLE
iOS Splash Screen

### ISSUE THREAD

**Issue by teatherconsulting** [yasirkula/UnityIonicIntegration#36]
We have tried a variety of iOS splash screen settings, but it seems that regardless of what we do we get a stretched version of the normal app splash screen when we open the Unity portion of our app.  Has anyone had any luck changing the Unity splash screen when using this plugin?

**Comment by yasirkula** [comment]
Did you resolve this issue?

**Comment by teatherconsulting** [comment]
No...we ended up giving up on doing the custom splash screen like we were hoping for.
