### ISSUE TITLE
iOS Unity part fails

### ISSUE THREAD

**Issue by palkens** [yasirkula/UnityIonicIntegration#37]
Hi,

I followed the tutorial with partial luck. The app builds and launch on iPhone X but when i press the button in Cordova part to launch Unity the app just closes. No error or something. 

Unity app is basic ARKit app to show model on table. 

I've added ARKit, min SDK is 11.4.

What else can i send you so you could help me?

EDIT
i moved forward with:
https://github.com/yasirkula/UnityIonicIntegration/issues/15
but now I get:
http://prntscr.com/ku5h7f

**Comment by palkens** [comment]
I managed to get this working ! I've changed target iOS version and make all steps one more time (well several times) and it's working!

**Comment by yasirkula** [comment]
Glad to hear it!
