### ISSUE TITLE
iOS : video frame is black (but sound is ok)

### ISSUE THREAD

**Issue by syc-pad** [yasirkula/UnityIonicIntegration#4]
Hi @yasirkula ,

I followed each step of your very precise and thorough tutorial for iOS, and I got absolutely **no problem**.
_(just a parenthesis : this time, on iOS, no dark Unity screen unlike android ;-) )_

My Unity project recognises a photo and play a video overlay (with music). I hear the music but the video frame remains black.

Someone has the same problem on StackOverflow, and they advise to disable multi-threading, but my Unity version is more recent, and I can't find this setting.
https://stackoverflow.com/questions/36563405/vuforia-video-playback-video-is-black?rq=1

It seems problem isn't due to your process, but I dare to ask : did you encounter the same problem ? :)

Thank you very much in advance.

**EDIT** : 
Oh, it works on an iPhone SE with iOS 10, but not with an iPodTouch on iOS 9.

**Comment by yasirkula** [comment]
It is located at Player Settings-Other Settings-Multithreaded Rendering. If you are playing from an imported video file, also make sure to tick the Transcode option of that video asset for your target platform.
