### ISSUE TITLE
EasyAR and VoidAR integration

### ISSUE THREAD

**Issue by juan9506** [yasirkula/UnityIonicIntegration#48]
Hi, this is not an issue, it's just to let you and the users know that this also works with EasyAR and VoidAR.
I already managed to make this work perfectly with those SDK's.
Here's how I did it:
*All the unity steps are the same, then, after building the project for gradle, you just have to add the following line in the dependencies of the build.gradle file of the Ionic project (platforms/android/build.gradle): 

For EasyAR:
`compile fileTree(dir: '/<path to your Unity exported project>/libs', include: 'EasyAR.jar')`

For VoidAR:
or `compile fileTree(dir: '/<path to your Unity exported project>/libs', include: 'VoidAR.jar')` 
Remember to change the path for your relative or absolute path.

![image](https://user-images.githubusercontent.com/38742067/53973176-42394180-40ce-11e9-9a25-203e7ab40c64.png)

Because if you don't reference the .jar file there, the module will close because it can't find the .jar classes.

* If you are using EasyAR, remember to match the BundleId or PackageName with the one that you used in the EasyAR platform, but when you are exporting from unity to gradle, you have to change these values for something else, and match the PackageName / BundleId on the EasyAR platform with the PackageName / BundleId of the Ionic / android project (present in AndroidManifest.xml and injected from config.xml) instead, because if you don't do this, you'll keep getting the "Invalid Key or Package Name" error.

**Comment by yasirkula** [comment]
Thank you for this informative guide!
