### ISSUE TITLE
ERROR: Couldn't find method compile() ...

### ISSUE THREAD

**Issue by cmaresh** [yasirkula/UnityIonicIntegration#52]
I am receiving this error when attempting to sync the gradle in Android Studio. I have made the suggested changes to the settings.gradle and android-level build.gradle files, as well as the changes to the AndroidManifest.xml in the Unity Project.

I did not see the applicationID line to be removed from the unity project build.gradle, or the manifests folder in the ionic build. 

Full error: ERROR: Could not find method compile() for arguments [project ':UnityProject'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

![unityionic](https://user-images.githubusercontent.com/5368740/59316669-3fc62500-8c85-11e9-8c67-814726d83cfd.PNG)

**Comment by darellbernabe** [comment]
Try moving the compile/implementation line in the build.gradle  under app folder. Make sure that you are putting it in the right 'dependecies' code block somewhere in line 200++

**Comment by cmaresh** [comment]
This resolved it, thank you. Readme may need to be changed to show that edit is made to platforms\android\app\build.gradle

**Comment by yasirkula** [comment]
I had used `platforms\android\build.gradle` in my tests. Glad the issue is resolved like this, though.

**Comment by yasirkula** [comment]
Updated the README.
