### ISSUE TITLE
iOS build failed Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by camin153** [yasirkula/UnityIonicIntegration#6]
I try to follow instruction for iOS. After I build project I recieve this error.

Undefined symbols for architecture arm64:
  "_UnitySetGraphicsDevice", referenced from:
      -[AppDelegate shouldAttachRenderDelegate] in AppDelegate.o
  "_UnityRenderEvent", referenced from:
      -[AppDelegate shouldAttachRenderDelegate] in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Do you have any suggestion?
<img width="570" alt="screen shot 2560-06-14 at 4 15 19 pm" src="https://user-images.githubusercontent.com/13098976/27124890-b7194d04-511c-11e7-8276-2e1af265aa32.png">

**Comment by Frobei** [comment]
Delete or put in comment the lines where UnitySetGraphicsDevice and UnityRenderEvent are used. It seems they're not necessary.

https://github.com/yasirkula/UnityIonicIntegration/issues/2

**Comment by camin153** [comment]
I try it, but it show only black screen. it didn't show even power by Unity screen.

**Comment by Frobei** [comment]
Just to make sure, you are trying to integrate a scene without using Vuforia right ?

Do you have something written in your log when you try to go into your unity view ?

**Comment by yasirkula** [comment]
I am planning to test the plugin without Vuforia myself next week. Until then, I hope you can solve this issue on your own.

**Comment by camin153** [comment]
I'm so sorry. It's my mistake in Ionic project. After I comment line of code in AppDelegate that have UnitySetGraphicsDevice and UnityRenderEvent. It works.

Thank you so much.
