### ISSUE TITLE
Type bitter.jnibridge.JNIBridge$a is defined multiple times

### ISSUE THREAD

**Issue by LasLamos** [yasirkula/UnityIonicIntegration#69]
**Description of the bug**

I'm currently working on a little project to integrate a unity app into an existing ionic app.
After adding the dependencies to the build.gradle file of the ionic app i get the error message:

Type bitter.jnibridge.JNIBridge$a is defined multiple times: ..\platforms\android\app\build\intermediates\external_file_lib_dex_archives\debug\out\0_unity-classes.jar:classes.dex, ..\platforms\android\app\build\intermediates\external_file_lib_dex_archives\debug\out\1_unity-classes.jar:classes.dex

**Reproduction steps**

What steps have i taken?

I edited the settings.gradle of the exported Ionic android project to look like this:
![image](https://user-images.githubusercontent.com/40241316/101452545-1d6e9f80-392e-11eb-8795-e81c99b93cee.png)

I edited the build.gradle dependency block of the exported Ionic Android project and added the implementation line:
![image](https://user-images.githubusercontent.com/40241316/101452731-73434780-392e-11eb-9db0-c09320180837.png)

I edited the UnityProject Gradle File and both AndroidManifests.
But every time i want to build the project, i get the error message above.

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: 2020.2.0b11*
- Platform: Android

-Ionic Info:
![image](https://user-images.githubusercontent.com/40241316/101453259-5d825200-392f-11eb-93ca-e6264b008eb5.png)

- How did you download the plugin: 
I downloaded the plugin with the 'ionic cordova add' command

Did anyone else get this error or knows how to fix it?

**Comment by yasirkula** [comment]
"absolute path to unityLibraryFolder" points to the folder you've selected when building your Unity project, right?

**Comment by LasLamos** [comment]
Yes, but i had to use the Path to the unityLibrary Folder inside UnityProject because i was getting an error that it could'nt be found.

**Comment by yasirkula** [comment]
That's probably why. I've always pointed it to the Unity build folder, not a subfolder of it nor a different folder. You should give more details about the library couldn't be found error.

**Comment by LasLamos** [comment]
If i'm setting everything to UnityProject just as the instruction says im getting this error:

Build file 'E:\Dennis\Desktop\IonicPlugin\UnityProject\build.gradle' line: 20

A problem occurred evaluating project ':UnityProject'.
> Project with path ':unityLibrary' could not be found in project ':UnityProject'.

Line 20 of E:\Dennis\Desktop\IonicPlugin\UnityProject\build.gradle:
```
flatDir {
            dirs "${project(':unityLibrary').projectDir}/libs"
        }
```

I Changed the Lines in setting.gradle to:
```
include ':UnityProject'
project(':UnityProject').projectDir = new File('E:\\Dennis\\Desktop\\IonicPlugin\\UnityProject')
```
And i changed the build.gradle dependencies to:
```
    implementation project(':UnityProject')
```

In my jniLibs Folder was no unity-classes.jar and there still isnt,

**Comment by yasirkula** [comment]
What is `:unityLibrary`? I can't find it in the documentation.

**Comment by LasLamos** [comment]
UnityLibrary is a subfolder in the exported UnityProject.
After eyxporting my UnityProject to an empty folder the structure looks like this:
![image](https://user-images.githubusercontent.com/40241316/101482641-4f482c00-3957-11eb-827a-79942d67ed10.png)

**Comment by yasirkula** [comment]
I think you should change flatDirs as follows:

```
flatDir {
   dirs 'E:\\Dennis\\Desktop\\IonicPlugin\\UnityProject\\libs'
}
```

**Comment by LasLamos** [comment]
If i'm editing the flatDirs i get yet another error, so im guessing something is messed up in my build.gradle files.
Maybe i should start a new Unity and Ionic Project and start with new Builds.



Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :UnityProject.
     Required by:
         project :app
      > No matching configuration of project :UnityProject was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' but:
          - None of the consumable configurations have attributes.

**Comment by LasLamos** [comment]
Okay, so i created a new UnityProject, added the IonicComms file and exported the project as an android project.
I created an new blank ionic project, added the plugin and added the codesnippet and build the android project.

After that i edited the settings.gradle and build.gradle of the ionic android export, but after clicking on 'Sync Now' im getting the same result:

![image](https://user-images.githubusercontent.com/40241316/101490559-d0f18700-3962-11eb-933d-3966cb314740.png)

And after editing the flatdirs as you suggested im getting the same error as before:

```
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :UnityProject.
     Required by:
         project :app
      > No matching configuration of project :UnityProject was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' but:
          - None of the consumable configurations have attributes.

```

**Comment by yasirkula** [comment]
I don't get it. Where does this `:unityLibrary` come from? I've shown you how you should replace that line in flatDir. Did you not apply that change?

**Comment by LasLamos** [comment]
As soon as i export my project from Unity, the folder has a unityLibrary folder in it:
![image](https://user-images.githubusercontent.com/40241316/101495896-642dbb00-3969-11eb-8e96-63ddf8e22139.png)


Within the exported UnityProject is a build.gradle, which contains the line:
```
            dirs "${project(':unityLibrary').projectDir}/libs"
```

which results in the mentioned error

I replaced the line as you suggested with 

```
flatDir {
   dirs 'E:\\Dennis\\Desktop\\IonicPlugin\\UnityProject\\unityLibrary'
}
```

and i tried the other suggestion as well:

```
flatDir {
   dirs 'E:\\Dennis\\Desktop\\IonicPlugin\\UnityProject\\libs'
}
```

But after applying the change to the flat dir, i get the error message i posted before:

```
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :UnityProject.
     Required by:
         project :app
      > No matching configuration of project :UnityProject was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' but:
          - None of the consumable configurations have attributes.
```


I'm sorry for any misunderstandings as english isnt my first language.
And thank you very much for your help so far!

**Comment by yasirkula** [comment]
Ah, so `:unityLibrary` comes with Unity, alright. I thought you were adding it to build.gradle. I think [Unity as a Library documentation](https://github.com/Unity-Technologies/uaal-example/blob/master/docs/android.md) will prove useful here. Please follow step 3 there. You'll probably have to change some/all occurrences of `:unityLibrary` there to `:UnityProject:unityLibrary`.

**Comment by LasLamos** [comment]
I followed the steps and changed all unityLibrary Occurences to your suggestion, but now i get the same error as in the beginning:

```
Type bitter.jnibridge.JNIBridge$a is defined multiple times: E:\Dennis\Desktop\New\android\app\build\intermediates\external_file_lib_dex_archives\debug\out\0_unity-classes.jar:classes.dex, E:\Dennis\Desktop\New\android\app\build\intermediates\external_file_lib_dex_archives\debug\out\1_unity-classes.jar:classes.dex
```

**Comment by yasirkula** [comment]
How many unity-classes.jar files are there in the Ionic build folder and the Unity build folder?

**Comment by LasLamos** [comment]
Ionic Build Folder:
One unity-classes.jar in 
```
E:\Dennis\Desktop\New\android\app\libs
```
And then there are these two:
![image](https://user-images.githubusercontent.com/40241316/101521422-1ecbb680-3986-11eb-8dfd-8abb88082dd0.png)
in 
```
E:\Dennis\Desktop\New\android\app\build\intermediates\external_file_lib_dex_archives\debug\out 
```
which the error is ponting to.


Unity Build Folder:
There are two unity-classes.jar
One in 
```
E:\Dennis\Desktop\New\UnityProject\unityLibrary\build\intermediates\aar_libs_directory\debug\libs
```
the other in
```
 E:\Dennis\Desktop\New\UnityProject\unityLibrary\libs
```

**Comment by yasirkula** [comment]
I'd expect `E:\Dennis\Desktop\New\android\app\libs` to show up in your project's jniLibs libs directory. If it does, try removing it from the project. If it doesn't, try deleting the file via file browser.

**Comment by LasLamos** [comment]
There is no unity-classes.jar in my jnilibs Folder.

But i removed unity-classis.jar from 
```
E:\Dennis\Desktop\New\android\app\libs
```

and now i build an launch the app!

I can't launch the unity application yet, but thats some different error im guessing is caused by my unity build options.

Thank you sou much for your help!

**Comment by yasirkula** [comment]
You are welcome! After finding the error, I'd recommend you to search it in this repository's Issues. If no similar issues exist and you think that the issue is related to Ionic integration, then feel free to create another Issue.
