### ISSUE TITLE
Make installable through git instead of local clone?

### ISSUE THREAD

**Issue by kevin-smets** [yasirkula/UnityIonicIntegration#7]
Could you restructure the repo so that you could add the plugin like this?

```
ionic cordova plugin add https://github.com/kevin-smets/UnityIonicIntegration.git#1.0.0
```

This is just a fork where I added a package.json and moved some resources around to make it installable remotely.

**Comment by yasirkula** [comment]
That would be great, for sure. I'll look into it soon, thanks :)

**Comment by yasirkula** [comment]
Hello Kevin,

Sorry for the long delay :-) Before I commit any changes, I wanted to ask whether the plugin is installable through git for your fork or not: https://github.com/kevin-smets/UnityIonicIntegration/tree/f6d724cb38cc525634bc3ae78885cc4ef9032a60

If so, I will reorganize files similar to yours and update the README accordingly.

Thank you.

**Comment by kevin-smets** [comment]
Hey, I just tried it on a clean project and it installed without issues. So my restructure should still be valid (tested with ionic v3.7.0).

**Comment by yasirkula** [comment]
I have restructured the repo accordingly and changed README slightly. Will try it on Monday. Thanks for all the help ^^
