### ISSUE TITLE
Just tested with a new project. Working with Ionic 3.9.2 . Only a minor fix needed

### ISSUE THREAD

**Issue by Miojo** [yasirkula/UnityIonicIntegration#8]
Thank you for this project. Your are a life saver.
I followed the documentation for android and worked great on Ionic 3.9.2 (still need to test with IoS). The only thinkg missing is that the plugin won't add without a "package.json" in the plugin folder. I followed  https://stackoverflow.com/a/44455103 to generate a simple package.json and it worked. Also there are some minor changes in the calls of ionic, instead of "ionic platform add" it is now "ionic cordova platform add".

**Comment by yasirkula** [comment]
That's great news, thanks for the info! Could you share your package.json here for reference?

**Comment by Miojo** [comment]
here... just remove the txt in the end
[package.json.txt](https://github.com/yasirkula/UnityIonicIntegration/files/1271386/package.json.txt)
