### ISSUE TITLE
Launcher does not work with a project with Ionic Storage

### ISSUE THREAD

**Issue by Miojo** [yasirkula/UnityIonicIntegration#9]
Simple to reproduce. I created a blank project with a button to open my unity app (android). Worked no problems.
Then added ionic storage to my project  https://ionicframework.com/docs/storage/ :
ionic cordova plugin add cordova-sqlite-storage
npm install --save @ionic/storage

Rebuilt my app... then when trying to open unity got an error message "Failure to initialize Your hardware does not support this application, sorry" (all on my physical device, s7 edge)

I think the root of the problem is that storage adds a bunch of folders under "android>jnilibs" folder 
![fff](https://user-images.githubusercontent.com/7649737/29942645-02bdd472-8e6d-11e7-9b5d-ed3d01fdea58.png)

**Comment by Miojo** [comment]
Some reference: https://forum.unity3d.com/threads/new-phone-unable-to-find-main-self-resolved.374473/

**Comment by yasirkula** [comment]
Unity provides a libunity.so file only for armeabi-v7a (32-bit ARM) architecture (and x86 architecture, if FAT or Intel is selected in Player Settings in Unity). 64-bit ARM architectures run 32-bit applications just fine as long as there are no 64-bit ARM specific plugins in your application. In that case, you receive the error you've posted. To fix this issue, simply delete the arm64-v8a, armeabi and x86_64 folders from your jniLibs folder.

**Comment by Miojo** [comment]
Worked! thanks :)
